version: "3.9"

services:
  backend:
    image: todo-api
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - backend-todo-api

  postgres:
    container_name: "todo-database"
    image: postgres
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "todo"
      POSTGRES_PASSWORD: "todo"
      POSTGRES_DB: "todo-db"
    ports:
      - "5429:5432"
    networks:
      - backend-todo-api

  mailhog:
    container_name: "todo-mailhog"
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - backend-todo-api


networks:
  backend-todo-api:
    name: todo-api-network

volumes:
  todo-db-data:
